version: '3'

services:
  db:
    image: postgres
    container_name: nyc-restaurant-grades-db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  rails:
    container_name: nyc-restaurant-grades-rails
    build:
      context: ../
      dockerfile: ./docker/rails/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env
    expose:
      - 3000
    networks:
      - backend
  nginx:
    container_name: nyc-restaurant-grades-nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - rails
    networks:
      - web
      - backend
    ports:
      - 3001:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:nyc-restaurant-grades.com"

volumes:
  db_data:

networks:
  backend:
  web:
    external: true
